#! /usr/bin/ruby

require 'src/chalk'
require 'highline/import'

puts "Chalk Test"
site = ask("Blackboard Server: "){|q| q.echo = true}
username = ask("Username: "){|q| q.echo = true}
password = ask("Enter Password: "){|q|q.echo = "*"}

bb = Chalk::Blackboard.new("https://" + site)
student = bb.login(username,password)
student.courses.map{|c| puts c[0]}
